---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:ramarahul/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: gcr.io/saas-brcm/hello-app
      tag: v4
    replicaCount: 1
    hpa:
      enabled: false
